### ISSUE TITLE
'is_safe_url' deprecated in Django 4.0

### ISSUE THREAD

**Issue by VirginiaDooley** [DemocracyClub/dc_signup_form#15]
This issue blocks  https://github.com/DemocracyClub/EveryElection/pull/1556
```
  File "/Users/virginiadooley/Documents/development/EveryElection/env/lib/python3.8/site-packages/dc_signup_form/urls.py", line 4, in <module>
    from .views import SignupFormView
  File "/Users/virginiadooley/Documents/development/EveryElection/env/lib/python3.8/site-packages/dc_signup_form/views.py", line 3, in <module>
    from django.utils.http import is_safe_url
ImportError: cannot import name 'is_safe_url' from 'django.utils.http' (/Users/virginiadooley/Documents/development/EveryElection/env/lib/python3.8/site-packages/django/utils/http.py)
```

change 

`from django.utils.http import is_safe_url`

to 

`from django.utils.http import url_has_allowed_host_and_scheme`

**Comment by symroe** [comment]
When working on this issue, remember we need to support older Django versions as well.

We have a couple of options here:

1. Release a new version that only support Django >4, and leave older Django versions to use older versions of this library. The problem with this is that any new feature we might add would only work in Django >4 (unless we backported them and maintained a different release cycle)
2. Use `a try/except` and catch `ImportError` to import the function, and then add our own wrapper between the code that uses it and the imported function name (or use `import...as foo` if it can be used in the same way)
